name: TDnet Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '35 23 * * *'
    - cron: '5 0 * * *'
    - cron: '35 2 * * *'
    - cron: '35 3 * * *'
    - cron: '5 6 * * *'
    - cron: '35 6 * * *'
    - cron: '5 7 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests beautifulsoup4

      - run: python monitor_TDnet.py
